from dataclasses import dataclass
from typing import Any


@dataclass
class Param:
    value: Any
    src:   str = None
    units: str = None
    notes: str = None


def P(value, src=None, units=None, notes=None):
    return Param(value, src=src, units=units, notes=notes)


PARAM_DICT = {

    "settings": {
        "max_age":       P(25,    notes="model internal"),
        "air_density":   P(1.225, units="kg/m3", notes="model internal"),
        "gravity":       P(9.81,  units="m/s2",  src="Table 7"),
        "start_year":    P(2025,  notes="model internal"),
        "end_year":      P(2050,  notes="model internal"),
        "discount_rate": P(0.08,  src="Table 7"),
        "growth_rate":   P(0.02,  src="Table 7"),
    },

    "fleet": {
        "initial_activity":      P(47361761620.2, units="t-km",
                                   src="UNREF -- paper (Table 8) shows 48.9 Gt-km; check units",
                                   notes="National Research Council, 2010; NRCan, 2025; Statistics Canada, 2009"),
        "activity_growth":       P(0.02,    src="Table 7"),
        "autonomous_t50":        P(2040,    notes="model uses 2040 point estimate; paper Table 10 shows triangular(2035,2040,2070) for scenario analysis"),
        "price_lambda":          P(0.00003, src="Table 7", notes="logit scale; market sensitivity"),
        "social_cost_of_carbon": P(59.276,  units="CAD/tCO2e", notes="model internal; not in Appendix A"),
        "revenue_markup":        P(1.2, src="UNREF -- assumption", units="dimensionless",
                                   notes="Freight revenue per t-km is set to this multiple of the "
                                         "prior year's realized system+policy cost per t-km"),
        "emissions_2007_factor": P(1.344827, units="dimensionless",
                                   src="Government of B.C., 2023b",
                                   notes="2025 BC HDT sector emissions / 2007 BC HDT sector emissions. "
                                         "Government of B.C. (2023b). Transportation Sector British Columbia "
                                         "and Territories Table 27: Truck Secondary Energy Use and GHG "
                                         "Emissions by Truck Type | Natural Resources Canada. "
                                         "https://oee.nrcan.gc.ca/corporate/statistics/neud/dpa/showTable.cfm"
                                         "?type=CP&sector=tran&juris=bct&year=2022&rn=27&page=0"),
    },

    "drive_cycles": {
        "long_haul": {
            "path":          P("param_estimation/energy_consumption/Fleet DNA Long-Haul Representative_.csv",
                               notes="model internal"),
            "average_speed": P(88.12, units="km/h",
                               src="National Research Council, 2010; NRCan, 2025; Statistics Canada, 2009"),
            "payload":       P(16000, units="kg",
                               src="National Research Council, 2010; NRCan, 2025; Statistics Canada, 2009"),
        },
        "regional_haul": {
            "path":          P("param_estimation/energy_consumption/Fleet DNA Regional-Haul Representative_.csv",
                               notes="model internal"),
            "average_speed": P(63.94, units="km/h",
                               src="National Research Council, 2010; NRCan, 2025; Statistics Canada, 2009"),
            "payload":       P(10000, units="kg",
                               src="National Research Council, 2010; NRCan, 2025; Statistics Canada, 2009"),
        },
        "short_haul": {
            "path":          P("param_estimation/energy_consumption/Fleet DNA Local Delivery Representative_.csv",
                               notes="model internal"),
            "average_speed": P(61.15, units="km/h",
                               src="National Research Council, 2010; NRCan, 2025; Statistics Canada, 2009"),
            "payload":       P(4000,  units="kg",
                               src="National Research Council, 2010; NRCan, 2025; Statistics Canada, 2009"),
        },
    },

    "fuels": {
        "diesel": {
            "units":   P("L"),
            "lhv":     P(38600000.0, src="S&T Squared, 2025; M. Wang et al., 2024", units="J/L"),
            "emissions_intensity": {
                "supply": P(0.88, src="S&T Squared, 2025; M. Wang et al., 2024", units="kgCO2e/L"),
                "use":    P(2.52, src="S&T Squared, 2025; M. Wang et al., 2024", units="kgCO2e/L"),
            },
            "refuel_efficiency":    P(1.0),
            "water_intensity":      P(2.95, src="S&T Squared, 2025; M. Wang et al., 2024", units="L/L"),
            "electricity_intensity": P(0.1, src="S&T Squared, 2025; M. Wang et al., 2024", units="kWh/L"),
            "cost": P(
                {"dist": "interp",
                 "2025": {"dist": "uniform", "min": 1.67, "max": 1.73},
                 "2030": {"dist": "uniform", "min": 1.46, "max": 1.81},
                 "2035": {"dist": "uniform", "min": 1.65, "max": 1.91},
                 "2040": {"dist": "uniform", "min": 1.74, "max": 2.08},
                 "2045": {"dist": "uniform", "min": 1.71, "max": 2.18},
                 "2050": {"dist": "uniform", "min": 1.67, "max": 2.15}},
                src="CER, 2023", units="CAD/L"),
        },

        "h2": {
            "units":   P("kg"),
            "lhv":     P(120000000.0, src="A. Franco et al., 2023; IRENA and Bluerisk, 2023", units="J/kg"),
            "emissions_intensity": {
                "supply": P(0.57, src="A. Franco et al., 2023; IRENA and Bluerisk, 2023", units="kgCO2e/kg"),
                "use":    P(0.0,  src="A. Franco et al., 2023; IRENA and Bluerisk, 2023", units="kgCO2e/kg"),
            },
            "refuel_efficiency":    P(1.0),
            "water_intensity":      P({"dist": "uniform", "min": 95.6, "max": 121.4},
                                      src="A. Franco et al., 2023; IRENA and Bluerisk, 2023", units="L/kg"),
            "electricity_intensity": P(55.0, src="A. Franco et al., 2023; IRENA and Bluerisk, 2023", units="kWh/kg"),
            "cost": P(
                {"dist": "interp",
                 "2025": {"dist": "const",   "val": 14.97},
                 "2030": {"dist": "uniform",  "min": 8.40,  "max": 11.13},
                 "2035": {"dist": "uniform",  "min": 6.55,  "max": 10.56},
                 "2040": {"dist": "uniform",  "min": 5.25,  "max": 6.34},
                 "2045": {"dist": "uniform",  "min": 5.20,  "max": 6.13},
                 "2050": {"dist": "uniform",  "min": 5.15,  "max": 5.94}},
                src="CICE, 2024", units="CAD/kg"),
        },

        "h2_p": {
            "units":   P("kg"),
            "lhv":     P(120000000.0, src="Serrato & Rowe, 2025; M. Wang et al., 2024", units="J/kg"),
            "emissions_intensity": {
                "supply": P(6.44, src="Serrato & Rowe, 2025; M. Wang et al., 2024", units="kgCO2e/kg"),
                "use":    P(0.0,  src="Serrato & Rowe, 2025; M. Wang et al., 2024", units="kgCO2e/kg"),
            },
            "refuel_efficiency":    P(1.0),
            "water_intensity":      P({"dist": "uniform", "min": 4.71, "max": 5.66},
                                      src="Serrato & Rowe, 2025; M. Wang et al., 2024", units="L/kg"),
            "electricity_intensity": P(2.12, src="Serrato & Rowe, 2025; M. Wang et al., 2024", units="kWh/kg"),
            "cost": P(
                {"dist": "interp",
                 "2025": {"dist": "const",   "val": 11.05},
                 "2030": {"dist": "uniform",  "min": 7.24,  "max": 7.38},
                 "2035": {"dist": "uniform",  "min": 5.41,  "max": 6.96},
                 "2040": {"dist": "uniform",  "min": 4.18,  "max": 5.21},
                 "2045": {"dist": "uniform",  "min": 2.91,  "max": 5.02},
                 "2050": {"dist": "uniform",  "min": 2.80,  "max": 4.85}},
                src="CICE, 2024", units="CAD/kg"),
        },

        "h2_pe": {
            "units":   P("kg"),
            "lhv":     P(120000000.0, src="Serrato & Rowe, 2025; Wang et al., 2024; Seymour et al., 2024", units="J/kg"),
            "emissions_intensity": {
                "supply": P(1.92, src="Serrato & Rowe, 2025; Wang et al., 2024; Seymour et al., 2024", units="kgCO2e/kg"),
                "use":    P(0.0,  src="Serrato & Rowe, 2025; Wang et al., 2024; Seymour et al., 2024", units="kgCO2e/kg"),
            },
            "refuel_efficiency":    P(1.0),
            "water_intensity":      P({"dist": "uniform", "min": 16.3, "max": 20.9},
                                      src="Serrato & Rowe, 2025; Wang et al., 2024; Seymour et al., 2024", units="L/kg"),
            "electricity_intensity": P(10.23, src="Serrato & Rowe, 2025; Wang et al., 2024; Seymour et al., 2024", units="kWh/kg"),
            "cost": P(
                {"dist": "interp",
                 "2025": {"dist": "const",   "val": 15.85},
                 "2030": {"dist": "uniform",  "min": 9.90,  "max": 11.81},
                 "2035": {"dist": "uniform",  "min": 7.86,  "max": 11.05},
                 "2040": {"dist": "uniform",  "min": 5.60,  "max": 7.48},
                 "2045": {"dist": "uniform",  "min": 4.75,  "max": 7.12},
                 "2050": {"dist": "uniform",  "min": 4.55,  "max": 6.81}},
                src="CICE, 2024", units="CAD/kg"),
        },

        "fast_charge": {
            "units":   P("kWh"),
            "lhv":     P(3600000.0, src="Government of B.C., 2025a; M. Wang et al., 2024", units="J/kWh"),
            "emissions_intensity": {
                "supply": P(0.0099, src="Government of B.C., 2025a; M. Wang et al., 2024", units="kgCO2e/kWh"),
                "use":    P(0.0,    src="Government of B.C., 2025a; M. Wang et al., 2024", units="kgCO2e/kWh"),
            },
            "refuel_efficiency":    P(0.86, src="Franca et al., 2018"),
            "water_intensity":      P({"dist": "uniform", "min": 1.43, "max": 1.88},
                                      src="Government of B.C., 2025a; M. Wang et al., 2024", units="L/kWh"),
            "electricity_intensity": P(1.0, units="kWh/kWh"),
            "cost": P(
                {"dist": "interp",
                 "2025": {"dist": "uniform", "min": 0.360, "max": 0.361},
                 "2030": {"dist": "uniform", "min": 0.368, "max": 0.372},
                 "2035": {"dist": "uniform", "min": 0.374, "max": 0.385},
                 "2040": {"dist": "uniform", "min": 0.382, "max": 0.397},
                 "2045": {"dist": "uniform", "min": 0.401, "max": 0.407},
                 "2050": {"dist": "uniform", "min": 0.412, "max": 0.418}},
                src="BC Hydro, 2025b; CER, 2023", units="CAD/kWh"),
        },

        "slow_charge": {
            "units":   P("kWh"),
            "lhv":     P(3600000.0, src="Government of B.C., 2025a; M. Wang et al., 2024", units="J/kWh"),
            "emissions_intensity": {
                "supply": P(0.0099, src="Government of B.C., 2025a; M. Wang et al., 2024", units="kgCO2e/kWh"),
                "use":    P(0.0,    src="Government of B.C., 2025a; M. Wang et al., 2024", units="kgCO2e/kWh"),
            },
            "refuel_efficiency":    P(0.95, src="Franca et al., 2018"),
            "water_intensity":      P({"dist": "uniform", "min": 1.43, "max": 1.88},
                                      src="Government of B.C., 2025a; M. Wang et al., 2024", units="L/kWh"),
            "electricity_intensity": P(1.0, units="kWh/kWh"),
            "cost": P(
                {"dist": "interp",
                 "2025": {"dist": "uniform", "min": 0.102, "max": 0.103},
                 "2030": {"dist": "uniform", "min": 0.105, "max": 0.106},
                 "2035": {"dist": "uniform", "min": 0.106, "max": 0.110},
                 "2040": {"dist": "uniform", "min": 0.109, "max": 0.113},
                 "2045": {"dist": "uniform", "min": 0.114, "max": 0.116},
                 "2050": {"dist": "uniform", "min": 0.117, "max": 0.119}},
                src="BC Hydro, 2025; CER, 2023", units="CAD/kWh"),
        },
    },

    "vehicles": {

        "components": {
            "converter": {
                "ice": {
                    "mass": P(1451, src="M. Wang et al., 2024", units="kg"),
                    "embodied_emissions": P(
                        {"dist": "interp", "group": "embodied",
                         "2025": {"dist": "const",    "val": 2.60},
                         "2050": {"dist": "triangle",  "min": 1.06, "mode": 2.01, "max": 2.60}},
                        src="Argonne GREET2, 2025 (MHDV_Comp_Sum, Class 8 Sleeper-Cab); decline trajectory from World Steel Association, 2025; IEA, 2020", units="kgCO2/kg"),
                    "efficiency": P(
                        {"dist": "interp",
                         "2000": {"dist": "const",   "val": 0.40},
                         "2010": {"dist": "const",   "val": 0.43},
                         "2025": {"dist": "const",   "val": 0.46},
                         "2030": {"dist": "uniform", "min": 0.49, "max": 0.51},
                         "2050": {"dist": "uniform", "min": 0.51, "max": 0.54}},
                        src="National Research Council, 2012; Meszler et al., 2018; Marcinkoski et al., 2019"),
                },
                "motor": {
                    "he": {
                        "mass": P(104, src="M. Wang et al., 2024", units="kg"),
                        "embodied_emissions": P(
                            {"dist": "interp", "group": "embodied",
                             "2025": {"dist": "const",   "val": 3.5},
                             "2050": {"dist": "triangle", "min": 1.43, "mode": 2.70, "max": 3.5}},
                            src="Argonne GREET2, 2025 (MHDV_Comp_Sum, Class 8 Sleeper-Cab); decline trajectory from World Steel Association, 2025; IEA, 2020", units="kgCO2/kg"),
                        "efficiency": P(0.875, src="Lajevardi et al., 2019",
                                        notes="includes inverter and motor"),
                    },
                    "hice": {
                        "mass": P(104, src="M. Wang et al., 2024", units="kg"),
                        "embodied_emissions": P(
                            {"dist": "interp", "group": "embodied",
                             "2025": {"dist": "const",   "val": 3.5},
                             "2050": {"dist": "triangle", "min": 1.43, "mode": 2.70, "max": 3.5}},
                            src="Argonne GREET2, 2025 (MHDV_Comp_Sum, Class 8 Sleeper-Cab); decline trajectory from World Steel Association, 2025; IEA, 2020", units="kgCO2/kg"),
                        "efficiency": P(0.875, src="Lajevardi et al., 2019",
                                        notes="includes inverter and motor"),
                    },
                    "fc": {
                        "mass": P(610, src="M. Wang et al., 2024", units="kg"),
                        "embodied_emissions": P(
                            {"dist": "interp", "group": "embodied",
                             "2025": {"dist": "const",   "val": 3.5},
                             "2050": {"dist": "triangle", "min": 1.43, "mode": 2.70, "max": 3.5}},
                            src="Argonne GREET2, 2025 (MHDV_Comp_Sum, Class 8 Sleeper-Cab); decline trajectory from World Steel Association, 2025; IEA, 2020", units="kgCO2/kg"),
                        "efficiency": P(0.875, src="Lajevardi et al., 2019",
                                        notes="includes inverter and motor"),
                    },
                    "be": {
                        "mass": P(537, src="M. Wang et al., 2024", units="kg"),
                        "embodied_emissions": P(
                            {"dist": "interp", "group": "embodied",
                             "2025": {"dist": "const",   "val": 3.5},
                             "2050": {"dist": "triangle", "min": 1.43, "mode": 2.70, "max": 3.5}},
                            src="Argonne GREET2, 2025 (MHDV_Comp_Sum, Class 8 Sleeper-Cab); decline trajectory from World Steel Association, 2025; IEA, 2020", units="kgCO2/kg"),
                        "efficiency": P(0.875, src="Lajevardi et al., 2019",
                                        notes="includes inverter and motor"),
                    },
                    "phe": {
                        "mass": P(175, src="M. Wang et al., 2024", units="kg"),
                        "embodied_emissions": P(
                            {"dist": "interp", "group": "embodied",
                             "2025": {"dist": "const",   "val": 3.5},
                             "2050": {"dist": "triangle", "min": 1.43, "mode": 2.70, "max": 3.5}},
                            src="Argonne GREET2, 2025 (MHDV_Comp_Sum, Class 8 Sleeper-Cab); decline trajectory from World Steel Association, 2025; IEA, 2020", units="kgCO2/kg"),
                        "efficiency": P(0.875, src="Lajevardi et al., 2019",
                                        notes="includes inverter and motor"),
                    },
                },
                "electronic_controller": {
                    "be": {
                        "mass": P(57, src="M. Wang et al., 2024", units="kg"),
                        "embodied_emissions": P(
                            {"dist": "interp", "group": "embodied",
                             "2025": {"dist": "const",   "val": 3.13},
                             "2050": {"dist": "triangle", "min": 1.28, "mode": 2.42, "max": 3.13}},
                            src="Argonne GREET2, 2025 (MHDV_Comp_Sum, Class 8 Sleeper-Cab); decline trajectory from World Steel Association, 2025; IEA, 2020", units="kgCO2/kg"),
                    },
                    "fc": {
                        "mass": P(64, src="M. Wang et al., 2024", units="kg"),
                        "embodied_emissions": P(
                            {"dist": "interp", "group": "embodied",
                             "2025": {"dist": "const",   "val": 3.13},
                             "2050": {"dist": "triangle", "min": 1.28, "mode": 2.42, "max": 3.13}},
                            src="Argonne GREET2, 2025 (MHDV_Comp_Sum, Class 8 Sleeper-Cab); decline trajectory from World Steel Association, 2025; IEA, 2020", units="kgCO2/kg"),
                    },
                    "he": {
                        "mass": P(11, src="M. Wang et al., 2024", units="kg"),
                        "embodied_emissions": P(
                            {"dist": "interp", "group": "embodied",
                             "2025": {"dist": "const",   "val": 3.13},
                             "2050": {"dist": "triangle", "min": 1.28, "mode": 2.42, "max": 3.13}},
                            src="Argonne GREET2, 2025 (MHDV_Comp_Sum, Class 8 Sleeper-Cab); decline trajectory from World Steel Association, 2025; IEA, 2020", units="kgCO2/kg"),
                    },
                },
                "fc": {
                    "mass": P(625, src="M. Wang et al., 2024", units="kg"),
                    "embodied_emissions": P(
                        {"dist": "interp", "group": "embodied",
                         "2025": {"dist": "const",   "val": 2.96},
                         "2050": {"dist": "triangle", "min": 1.21, "mode": 2.29, "max": 2.96}},
                        src="Argonne GREET2, 2025 (MHDV_Comp_Sum, Class 8 Sleeper-Cab); decline trajectory from World Steel Association, 2025; IEA, 2020", units="kgCO2/kg"),
                    "efficiency": P(
                        {"dist": "interp",
                         "2025": {"dist": "const",   "val": 0.59},
                         "2030": {"dist": "uniform", "min": 0.59, "max": 0.63},
                         "2050": {"dist": "uniform", "min": 0.63, "max": 0.66}},
                        src="Marcinkoski et al., 2019"),
                    "lifetime": P(
                        {"dist": "interp",
                         "2025": {"dist": "const",    "val": 20000},
                         "2030": {"dist": "triangle",  "min": 22500, "mode": 25000, "max": 27500},
                         "2050": {"dist": "triangle",  "min": 27500, "mode": 30000, "max": 32500}},
                        src="Marcinkoski et al., 2019", units="hours"),
                },
            },

            "ess": {
                "diesel_tank": {
                    "specific_mass":        P(0.0,  notes="model internal; included in powertrain mass"),
                    "embodied_emissions":   P(0.0,  notes="model internal; included in powertrain mass"),
                    "usable_capacity":      P(0.95, notes="model internal"),
                    "refuel_rate":          P(6000, units="L/min", notes="model internal"),
                },
                "battery": {
                    "specific_mass": P(
                        {"dist": "interp",
                         "2025": {"dist": "const",    "val": 6.0},
                         "2035": {"dist": "uniform",  "min": 3.34, "max": 5.57},
                         "2050": {"dist": "triangle", "min": 1.74, "mode": 3.34, "max": 5.57}},
                        src="Haghbin et al., 2025; Jose et al., 2025; Tiede et al., 2022",
                        units="kg/kWh",
                        notes="67% increase on cell level; solid state majority by 2035; advanced chemistries potential by 2050"),
                    "embodied_emissions": P(
                        {"dist": "linear", "group": "embodied",
                         "start": {"dist": "const",   "val": 87.0},
                         "end":   {"dist": "uniform", "min": 20.0, "max": 40.0}},
                        src="World Steel Association, 2025; IEA, 2020", units="kgCO2/kWh"),
                    "usable_capacity": P(
                        {"dist": "interp",
                         "2025": {"dist": "const",   "val": 0.8},
                         "2030": {"dist": "uniform", "min": 0.85, "max": 0.90},
                         "2050": {"dist": "uniform", "min": 0.9,  "max": 0.95}},
                        src="Table 15"),
                    "refuel_rate": P(
                        {"dist": "linear",
                         "start": {"dist": "const",    "val": 250.0},
                         "end":   {"dist": "triangle", "min": 250.0, "mode": 500.0, "max": 750.0}},
                        src="Table 15", units="kW",
                        notes="en-route re-fuelling only"),
                    "efficiency":      P(1.0),
                    "efficiency_deg":  P(0.0),
                    "deg_per_year":    P(0.01,    src="NREL, 2023", notes="1%/yr"),
                    "deg_per_cycle":   P(0.00002, src="NREL, 2023", notes="0.002%/cycle"),
                },
                "h2_700bar": {
                    "specific_mass": P(
                        {"dist": "interp", "2025": 18.5, "2050": 15.1},
                        src="Simmons et al., 2025; M. Wang et al., 2024", units="kg/kgH2",
                        notes="sleeper/FCET"),
                    "embodied_emissions": P(
                        {"dist": "linear", "group": "embodied",
                         "start": {"dist": "const",    "val": 14.68},
                         "end":   {"dist": "triangle", "min": 6.01, "mode": 11.34, "max": 14.68}},
                        src="Argonne GREET2, 2025 (MHDV_Comp_Sum, Class 8 Sleeper-Cab: Hydrogen Storage System); decline trajectory from World Steel Association, 2025; IEA, 2020", units="kgCO2/kg"),
                    "usable_capacity": P(0.9, src="Table 16"),
                    "refuel_rate":     P(480, src="Table 16", units="kg/hr"),
                },
                "h2_350bar": {
                    "specific_mass": P(
                        {"dist": "interp", "2025": 16.0, "2050": 13.0},
                        src="Simmons et al., 2025; M. Wang et al., 2024", units="kg/kgH2",
                        notes="day-cab and straight truck"),
                    "embodied_emissions": P(
                        {"dist": "linear", "group": "embodied",
                         "start": {"dist": "const",    "val": 14.68},
                         "end":   {"dist": "triangle", "min": 6.01, "mode": 11.34, "max": 14.68}},
                        src="Argonne GREET2, 2025 (MHDV_Comp_Sum, Class 8 Sleeper-Cab: Hydrogen Storage System); decline trajectory from World Steel Association, 2025; IEA, 2020", units="kgCO2/kg"),
                    "usable_capacity": P(0.9, src="Table 17"),
                    "refuel_rate":     P(480, src="Table 17", units="kg/hr"),
                },
            },

            "transmission": {
                "combustion_transmission": {
                    "efficiency": P(0.95, src="Gilleon et al., 2022"),
                    "mass":       P(445,  src="M. Wang et al., 2024", units="kg"),
                    "embodied_emissions": P(
                        {"dist": "interp", "group": "embodied",
                         "2025": {"dist": "const",   "val": 2.45},
                         "2050": {"dist": "triangle", "min": 1.00, "mode": 1.89, "max": 2.45}},
                        src="Argonne GREET2, 2025 (MHDV_Comp_Sum, Class 8 Sleeper-Cab); decline trajectory from World Steel Association, 2025; IEA, 2020", units="kgCO2/kg"),
                },
                "electric_transmission": {
                    "efficiency": P(0.97,
                                    src="UNREF -- paper (Table 14) shows 96%; params.py uses 0.97"),
                    "mass":       P(204, src="M. Wang et al., 2024", units="kg"),
                    "embodied_emissions": P(
                        {"dist": "interp", "group": "embodied",
                         "2025": {"dist": "const",   "val": 2.45},
                         "2050": {"dist": "triangle", "min": 1.00, "mode": 1.89, "max": 2.45}},
                        src="Argonne GREET2, 2025 (MHDV_Comp_Sum, Class 8 Sleeper-Cab); decline trajectory from World Steel Association, 2025; IEA, 2020", units="kgCO2/kg"),
                },
            },

            "accessories": {
                "after_treatment": {},
            },

            "frame": {
                "embodied_emissions": P(
                    {"dist": "interp", "group": "embodied",
                     "2025": {"dist": "const",    "val": 3.83},
                     "2050": {"dist": "triangle", "min": 1.57, "mode": 2.96, "max": 3.83}},
                    src="Argonne GREET2, 2025 (MHDV_Comp_Sum, Class 8 Sleeper-Cab: Chassis w/o battery + Body combined); decline trajectory from World Steel Association, 2025; IEA, 2020",
                    units="kgCO2/kg",
                    notes="shared across vehicle types; each vehicle type supplies its own frame_mass"),
            },

            "trailer": {
                "embodied_emissions": P(
                    {"dist": "interp", "group": "embodied",
                     "2025": {"dist": "const",    "val": 3.78},
                     "2050": {"dist": "triangle", "min": 1.55, "mode": 2.92, "max": 3.78}},
                    src="Argonne GREET2, 2025 (MHDV_Trailer_Comp_Sum: Body + Chassis + Auxiliary, mass-weighted by one-time material composition, not GREET's own per-lifetime total which bundles tire replacements into Chassis); decline trajectory from World Steel Association, 2025; IEA, 2020",
                    units="kgCO2/kg",
                    notes="shared across sleeper/day_cab (the only vehicle types with a trailer); each supplies its own trailer_mass"),
            },

            "tire": {
                "embodied_emissions": P(
                    {"dist": "interp", "group": "embodied",
                     "2025": {"dist": "const",    "val": 3.30},
                     "2050": {"dist": "triangle", "min": 1.35, "mode": 2.55, "max": 3.30}},
                    src="Argonne GREET2, 2025 (MHDV_Comp_Sum/MHDV_Trailer_Comp_Sum: 66.7% rubber, 33.3% steel, uniform across steer/drive/trailer tires); decline trajectory from World Steel Association, 2025; IEA, 2020",
                    units="kgCO2/kg",
                    notes="shared across all tire positions and vehicle types; lifetime tire-replacement mass (not instantaneous physical mass) supplied per vehicle type via tire_mass/trailer_tire_mass"),
            },
        },

        "costs": {
            "diesel_engine":           P(35000, src="H. Zhao et al., 2018",  units="CAD"),
            "combustion_transmission": P(13700, src="H. Zhao et al., 2018",  units="CAD"),
            "electric_transmission":   P(3200,  src="H. Zhao et al., 2018",  units="CAD"),
            "after_treatment":         P(12000, src="BCTA, 2019",            units="CAD"),
            "tank":                    P(9.44,  src="Lajevardi et al., 2019", units="CAD/L"),
            "motor":                   P(40,    src="H. Zhao et al., 2018",  units="CAD/kW"),
            "battery": P(
                {"dist": "linear",
                 "start": {"dist": "const",    "val": 159.0},
                 "end":   {"dist": "triangle", "min": 81.0, "mode": 101.0, "max": 157.0}},
                src="BloombergNEF, 2024; Mauler et al., 2021", units="CAD/kWh"),
            "h2_700bar": P(
                {"dist": "interp",
                 "2025": {"dist": "uniform", "min": 625.0, "max": 686.0},
                 "2030": {"dist": "uniform", "min": 498.0, "max": 625.0},
                 "2050": {"dist": "uniform", "min": 442.0, "max": 498.0}},
                src="Simmons et al., 2025; Marcinkoski et al., 2019", units="CAD/kg"),
            "h2_350bar": P(
                {"dist": "interp",
                 "2025": {"dist": "uniform", "min": 625.0, "max": 686.0},
                 "2030": {"dist": "uniform", "min": 498.0, "max": 625.0},
                 "2050": {"dist": "uniform", "min": 442.0, "max": 498.0}},
                src="Simmons et al., 2025; Marcinkoski et al., 2019", units="CAD/kg"),
            "fc": P(
                {"dist": "interp",
                 "2025": {"dist": "uniform", "min": 357.0,  "max": 500.0},
                 "2030": {"dist": "uniform", "min": 146.0,  "max": 285.0},
                 "2040": {"dist": "uniform", "min": 100.0,  "max": 201.0},
                 "2050": {"dist": "uniform", "min": 79.0,   "max": 146.0}},
                src="Kleen & Gibbons, 2024", units="CAD/kW"),
            "hice_engine": P(
                {"dist": "interp",
                 "2025": {"dist": "const", "val": 43750.0},
                 "2050": {"dist": "const", "val": 35000.0}},
                src="H. Zhao et al., 2018; DESNZ, 2024", units="CAD"),
            "charger_50kw": P(
                {"dist": "interp",
                 "2025": {"dist": "const",   "val":  60000.0},
                 "2030": {"dist": "uniform", "min":  50000.0, "max": 54000.0},
                 "2040": {"dist": "uniform", "min":  44000.0, "max": 49000.0},
                 "2050": {"dist": "uniform", "min":  30000.0, "max": 37000.0}},
                src="UNREF -- paper (Table 20) shows 2030 max = 60,000; params.py uses 54,000. Perrault & Scholz, 2024; Recharged, 2025",
                units="CAD"),
        },

        "types": {

            "sleeper": {
                "shared": {
                    "max_age":               P(25,         notes="model internal"),
                    "activity_proportion":   P(0.762745,   src="National Research Council, 2010; NRCan, 2025; Statistics Canada, 2009"),
                    "default_unloaded_mass": P(12938,      units="kg", notes="model internal"),
                    "gvwl":                  P(53500,      src="COMT, 2019", units="kg",
                                               notes="Category 7: Truck - Full Trailer"),
                    "target_distance": P(
                        {"array": "logistic", "max_val": 208714, "min_val": 17478,
                         "k": 0.372, "x0": 7.62},
                        src="Statistics Canada, 2009", units="km",
                        notes="logistic fit to CVS mileage-vs-age data"),
                    "revenue_per_tkm":   P(0.10,  src="Table 21", units="CAD/t-km"),
                    "trailers_per_truck": P(3,    src="National Research Council, 2010"),
                    "drive_cycle": P(
                        {"array": "step", "threshold": 10,
                         "below": "long_haul", "above": "regional_haul"},
                        notes="model internal"),
                    "survival_rate": P(
                        {"array": "linspace", "start": 1.0, "end": 0.0},
                        src="Statistics Canada, 2009",
                        notes="linear decline from 100% to 0% over max_age years"),
                    "frontal_area":       P(9.2,   src="National Academics, 2020", units="m2"),
                    "roll_coef":          P(0.0054, notes="model internal"),
                    "frame_mass":         P(6051,  src="UNREF -- paper (Table 11) shows 6,052 kg; M. Wang et al., 2024",
                                            units="kg"),
                    "trailer_mass":       P(5029,  src="M. Wang et al., 2024", units="kg"),
                    "tire_mass":          P(2068.38, src="Argonne GREET2, 2025 (MHDV_Comp_Sum, Class 8 Sleeper-Cab: steer 7 replacements x 2 tires + drive 3 x 8, @ 120 lbs/tire)",
                                            units="kg", notes="lifetime tire-replacement mass, not instantaneous physical mass"),
                    "trailer_tire_mass":  P(4354.49, src="Argonne GREET2, 2025 (MHDV_Trailer_Comp_Sum: 10 replacements x 8 tires @ 120 lbs/tire)",
                                            units="kg", notes="tire wear is distance-driven, not swap-driven; NOT multiplied by trailers_per_truck, unlike the trailer's own structural mass"),
                    "mass_correction":    P(0.2,   src="Gilleon et al., 2022"),
                    "p_weighed_out":      P(0.3,   src="EPA, 2011"),
                    "driver_cost":        P(0.38,  src="Table 21", units="CAD/km",
                                            notes="informed by communication with BC Trucking Association"),
                    "drag_coef": P(
                        {"dist": "interp",
                         "2000": {"dist": "const",   "val": 0.7},
                         "2010": {"dist": "const",   "val": 0.6},
                         "2025": {"dist": "const",   "val": 0.49},
                         "2030": {"dist": "uniform", "min": 0.34, "max": 0.43},
                         "2050": {"dist": "uniform", "min": 0.30, "max": 0.41}},
                        src="Marcinkoski et al., 2019"),
                    "pollution_cost": {
                        "NOX":  P(26058,  notes="model internal; not in Appendix A"),
                        "NMVC": P(2428,   notes="model internal; not in Appendix A"),
                        "SO2":  P(25542,  notes="model internal; not in Appendix A"),
                        "PM":   P(144770, notes="model internal; not in Appendix A"),
                        "PMNE": P(46120,  notes="model internal; not in Appendix A"),
                    },
                    "base_cost": P(163000, src="H. Zhao et al., 2018; Transport Canada, 2018",
                                   units="CAD"),
                },
                "powertrains": {
                    "dice": {
                        "components": {
                            "ice":                     {"type": "converter"},
                            "diesel_tank":             {"type": "ess",          "capacity": 500},
                            "combustion_transmission": {"type": "transmission"},
                            "after_treatment":         {"type": "accessories"},
                        },
                        "fuels": {"diesel": {"proportion": 1.0}},
                        "regen_efficiency": P(0.0),
                        "accessory_load":   P(4250, src="Ramesh Babu et al., 2025", units="W",
                                              notes="25% increase vs hybrid; Lajunen, 2014"),
                        "running_cost":     P(0.17, src="H. Zhao et al., 2018", units="CAD/km"),
                        "init_market_limit": P(1.0, notes="model internal"),
                        "cagr_nacent": P({"dist": "uniform", "min": 0.44, "max": 0.54},
                                         src="MarketsandMarkets, 2024"),
                        "cagr_mature": P({"dist": "uniform", "min": 0.34, "max": 0.38},
                                         src="MarketsandMarkets, 2024"),
                    },
                    "he": {
                        "components": {
                            "ice":                     {"type": "converter"},
                            "motor":                   {"type": "converter", "capacity": 220},
                            "diesel_tank":             {"type": "ess",       "capacity": 500},
                            "battery":                 {"type": "ess",       "capacity": 10},
                            "combustion_transmission": {"type": "transmission"},
                            "after_treatment":         {"type": "accessories"},
                        },
                        "fuels": {"diesel": {"proportion": 1.0}},
                        "regen_efficiency": P(0.71, src="Table 14", notes="power-limited"),
                        "accessory_load":   P(3400, src="Ramesh Babu et al., 2025", units="W"),
                        "running_cost":     P(0.17, src="H. Zhao et al., 2018", units="CAD/km"),
                        "init_market_limit": P(0.02, notes="model internal"),
                        "cagr_nacent": P({"dist": "uniform", "min": 0.44, "max": 0.54},
                                         src="MarketsandMarkets, 2024"),
                        "cagr_mature": P({"dist": "uniform", "min": 0.34, "max": 0.38},
                                         src="MarketsandMarkets, 2024"),
                    },
                    "phe": {
                        "components": {
                            "ice":                     {"type": "converter"},
                            "motor":                   {"type": "converter", "capacity": 350},
                            "diesel_tank":             {"type": "ess",       "capacity": 500},
                            "battery":                 {"type": "ess",       "capacity": 300},
                            "combustion_transmission": {"type": "transmission"},
                            "after_treatment":         {"type": "accessories"},
                        },
                        "fuels": {
                            "fast_charge": {"proportion": 0.5},
                            "diesel":      {"proportion": 0.5},
                        },
                        "regen_efficiency": P(0.71, src="Table 14", notes="power-limited"),
                        "accessory_load":   P(3400, src="Ramesh Babu et al., 2025", units="W"),
                        "running_cost":     P(0.17, src="H. Zhao et al., 2018", units="CAD/km"),
                        "init_market_limit": P(0.02, notes="model internal"),
                        "cagr_nacent": P({"dist": "uniform", "min": 0.44, "max": 0.54},
                                         src="MarketsandMarkets, 2024"),
                        "cagr_mature": P({"dist": "uniform", "min": 0.34, "max": 0.38},
                                         src="MarketsandMarkets, 2024"),
                    },
                    "be": {
                        "components": {
                            "motor":                  {"type": "converter",    "capacity": 880},
                            "electronic_controller":  {"type": "converter"},
                            "battery":                {"type": "ess",          "capacity": 1000},
                            "electric_transmission":  {"type": "transmission"},
                        },
                        "fuels": {"fast_charge": {"proportion": 1.0}},
                        "regen_efficiency": P(0.71, src="Table 15", notes="power-limited"),
                        "accessory_load":   P(6900, src="Ramesh Babu et al., 2025", units="W"),
                        "running_cost":     P(0.12, src="H. Zhao et al., 2018", units="CAD/km"),
                        "init_market_limit": P(0.02, notes="model internal"),
                        "cagr_nacent": P({"dist": "uniform", "min": 0.35, "max": 0.49},
                                         src="Link et al., 2024"),
                        "cagr_mature": P({"dist": "uniform", "min": 0.25, "max": 0.29},
                                         src="Link et al., 2024"),
                    },
                    "fc": {
                        "components": {
                            "fc":                    {"type": "converter",    "capacity": 880},
                            "motor":                 {"type": "converter",    "capacity": 880},
                            "electronic_controller": {"type": "converter"},
                            "h2_700bar":             {"type": "ess",          "capacity": 80},
                            "battery":               {"type": "ess",          "capacity": 5},
                            "electric_transmission": {"type": "transmission"},
                        },
                        "fuels": {"h2": {"proportion": 1.0}},
                        "regen_efficiency": P(0.71, src="Table 16", notes="power-limited"),
                        "accessory_load":   P(3400, src="Ramesh Babu et al., 2025", units="W"),
                        "running_cost":     P(0.14, src="H. Zhao et al., 2018", units="CAD/km"),
                        "init_market_limit": P(0.02, notes="model internal"),
                        "cagr_nacent": P({"dist": "uniform", "min": 0.35, "max": 0.49},
                                         src="Link et al., 2024"),
                        "cagr_mature": P({"dist": "uniform", "min": 0.25, "max": 0.29},
                                         src="Link et al., 2024"),
                    },
                    "hice": {
                        "components": {
                            "ice":                     {"type": "converter"},
                            "motor":                   {"type": "converter",    "capacity": 220},
                            "h2_700bar":               {"type": "ess",          "capacity": 90},
                            "battery":                 {"type": "ess",          "capacity": 10},
                            "combustion_transmission": {"type": "transmission"},
                        },
                        "fuels": {"h2": {"proportion": 1.0}},
                        "regen_efficiency": P(0.71, src="Table 17", notes="power-limited"),
                        "accessory_load":   P(3400,
                                              src="UNREF -- paper (Table 17) shows 4,250 W; params.py uses 3,400 W",
                                              units="W"),
                        "running_cost":     P(0.17, src="H. Zhao et al., 2018", units="CAD/km"),
                        "init_market_limit": P(0.02, notes="model internal"),
                        "cagr_nacent": P({"dist": "uniform", "min": 0.44, "max": 0.54},
                                         src="MarketsandMarkets, 2024"),
                        "cagr_mature": P({"dist": "uniform", "min": 0.34, "max": 0.38},
                                         src="MarketsandMarkets, 2024"),
                    },
                    "dhice": {
                        "components": {
                            "ice":                     {"type": "converter"},
                            "diesel_tank":             {"type": "ess",          "capacity": 500},
                            "h2_350bar":               {"type": "ess",          "capacity": 20},
                            "combustion_transmission": {"type": "transmission"},
                            "after_treatment":         {"type": "accessories"},
                        },
                        "fuels": {
                            "diesel": {"proportion": 0.75},
                            "h2":     {"proportion": 0.25},
                        },
                        "regen_efficiency": P(0.0),
                        "accessory_load":   P(4250, src="Ramesh Babu et al., 2025", units="W"),
                        "running_cost":     P(0.17, src="H. Zhao et al., 2018", units="CAD/km"),
                        "init_market_limit": P(0.02, notes="model internal"),
                        "cagr_nacent": P({"dist": "uniform", "min": 0.44, "max": 0.54},
                                         src="MarketsandMarkets, 2024"),
                        "cagr_mature": P({"dist": "uniform", "min": 0.34, "max": 0.38},
                                         src="MarketsandMarkets, 2024"),
                    },
                },
            },

            "day_cab": {
                "shared": {
                    "max_age":               P(25,         notes="model internal"),
                    "activity_proportion":   P(0.175363,   src="National Research Council, 2010; NRCan, 2025; Statistics Canada, 2009"),
                    "default_unloaded_mass": P(12266,      units="kg", notes="model internal"),
                    "gvwl":                  P(53500,      src="COMT, 2019", units="kg",
                                               notes="Category 7: Truck - Full Trailer"),
                    "target_distance": P(
                        {"array": "logistic", "max_val": 137922, "min_val": 11551,
                         "k": 0.372, "x0": 7.62},
                        src="Statistics Canada, 2009", units="km"),
                    "revenue_per_tkm":    P(0.17, src="Table 21", units="CAD/t-km"),
                    "trailers_per_truck": P(3,    src="National Research Council, 2010"),
                    "drive_cycle": P(
                        {"array": "constant", "value": "regional_haul"},
                        notes="model internal"),
                    "survival_rate": P(
                        {"array": "linspace", "start": 1.0, "end": 0.0},
                        src="Statistics Canada, 2009"),
                    "frontal_area":       P(9.2,   src="National Academics, 2020", units="m2"),
                    "roll_coef":          P(0.0054, notes="model internal"),
                    "frame_mass":         P(5380,  src="M. Wang et al., 2024", units="kg"),
                    "trailer_mass":       P(5029,  src="M. Wang et al., 2024", units="kg"),
                    "tire_mass":          P(1366.83, src="Argonne GREET2, 2025 sleeper tire schedule (2068.38 kg) scaled by day_cab/sleeper survival-weighted lifetime distance ratio (0.661) x wheel-count ratio (10/10 = 1.0; same 3-axle tractor as sleeper per GREET's Class 8 Day-Cab Trucks)",
                                            units="kg", notes="lifetime tire-replacement mass, not instantaneous physical mass"),
                    "trailer_tire_mass":  P(4354.49, src="Argonne GREET2, 2025 (MHDV_Trailer_Comp_Sum: 10 replacements x 8 tires @ 120 lbs/tire; same trailer as sleeper)",
                                            units="kg", notes="tire wear is distance-driven, not swap-driven; NOT multiplied by trailers_per_truck, unlike the trailer's own structural mass"),
                    "mass_correction":    P(0.2,   src="Gilleon et al., 2022"),
                    "p_weighed_out":      P(0.3,   src="EPA, 2011"),
                    "driver_cost":        P(0.48, src="Table 21", units="CAD/km",
                                            notes="informed by communication with BC Trucking Association"),
                    "drag_coef": P(
                        {"dist": "interp",
                         "2000": {"dist": "const",   "val": 0.7},
                         "2010": {"dist": "const",   "val": 0.6},
                         "2025": {"dist": "const",   "val": 0.49},
                         "2030": {"dist": "uniform", "min": 0.34, "max": 0.43},
                         "2050": {"dist": "uniform", "min": 0.30, "max": 0.41}},
                        src="Marcinkoski et al., 2019"),
                    "pollution_cost": {
                        "NOX":  P(35054.5, notes="model internal; not in Appendix A"),
                        "NMVC": P(2482,    notes="model internal; not in Appendix A"),
                        "SO2":  P(25542,   notes="model internal; not in Appendix A"),
                        "PM":   P(199576.5, notes="model internal; not in Appendix A"),
                        "PMNE": P(46120,   notes="model internal; not in Appendix A"),
                    },
                    "base_cost": P(153000, src="H. Zhao et al., 2018; Transport Canada, 2018",
                                   units="CAD"),
                },
                "powertrains": {
                    "dice": {
                        "components": {
                            "ice":                     {"type": "converter"},
                            "diesel_tank":             {"type": "ess",          "capacity": 500},
                            "combustion_transmission": {"type": "transmission"},
                            "after_treatment":         {"type": "accessories"},
                        },
                        "fuels": {"diesel": {"proportion": 1.0}},
                        "regen_efficiency": P(0.0),
                        "accessory_load":   P(4250, src="Ramesh Babu et al., 2025", units="W"),
                        "running_cost":     P(0.17, src="H. Zhao et al., 2018", units="CAD/km"),
                        "init_market_limit": P(1.0, notes="model internal"),
                        "cagr_nacent": P({"dist": "uniform", "min": 0.44, "max": 0.54},
                                         src="MarketsandMarkets, 2024"),
                        "cagr_mature": P({"dist": "uniform", "min": 0.34, "max": 0.38},
                                         src="MarketsandMarkets, 2024"),
                    },
                    "he": {
                        "components": {
                            "ice":                     {"type": "converter"},
                            "motor":                   {"type": "converter", "capacity": 220},
                            "diesel_tank":             {"type": "ess",       "capacity": 500},
                            "battery":                 {"type": "ess",       "capacity": 5},
                            "combustion_transmission": {"type": "transmission"},
                            "after_treatment":         {"type": "accessories"},
                        },
                        "fuels": {"diesel": {"proportion": 1.0}},
                        "regen_efficiency": P(0.71, src="Table 14", notes="power-limited"),
                        "accessory_load":   P(3400, src="Ramesh Babu et al., 2025", units="W"),
                        "running_cost":     P(0.17, src="H. Zhao et al., 2018", units="CAD/km"),
                        "init_market_limit": P(0.02, notes="model internal"),
                        "cagr_nacent": P({"dist": "uniform", "min": 0.44, "max": 0.54},
                                         src="MarketsandMarkets, 2024"),
                        "cagr_mature": P({"dist": "uniform", "min": 0.34, "max": 0.38},
                                         src="MarketsandMarkets, 2024"),
                    },
                    "phe": {
                        "components": {
                            "ice":                     {"type": "converter"},
                            "motor":                   {"type": "converter", "capacity": 350},
                            "diesel_tank":             {"type": "ess",       "capacity": 500},
                            "battery":                 {"type": "ess",       "capacity": 200},
                            "combustion_transmission": {"type": "transmission"},
                            "after_treatment":         {"type": "accessories"},
                        },
                        "fuels": {
                            "slow_charge": {"proportion": 0.5},
                            "diesel":      {"proportion": 0.5},
                        },
                        "regen_efficiency": P(0.71, src="Table 14", notes="power-limited"),
                        "accessory_load":   P(3400, src="Ramesh Babu et al., 2025", units="W"),
                        "running_cost":     P(0.17, src="H. Zhao et al., 2018", units="CAD/km"),
                        "init_market_limit": P(0.02, notes="model internal"),
                        "cagr_nacent": P({"dist": "uniform", "min": 0.44, "max": 0.54},
                                         src="MarketsandMarkets, 2024"),
                        "cagr_mature": P({"dist": "uniform", "min": 0.34, "max": 0.38},
                                         src="MarketsandMarkets, 2024"),
                    },
                    "be": {
                        "components": {
                            "motor":                 {"type": "converter",    "capacity": 880},
                            "electronic_controller": {"type": "converter"},
                            "battery":               {"type": "ess",          "capacity": 600},
                            "electric_transmission": {"type": "transmission"},
                        },
                        "fuels": {"slow_charge": {"proportion": 1.0}},
                        "regen_efficiency": P(0.71, src="Table 15", notes="power-limited"),
                        "accessory_load":   P(6900, src="Ramesh Babu et al., 2025", units="W"),
                        "running_cost":     P(0.12, src="H. Zhao et al., 2018", units="CAD/km"),
                        "init_market_limit": P(0.02, notes="model internal"),
                        "cagr_nacent": P({"dist": "uniform", "min": 0.35, "max": 0.49},
                                         src="Link et al., 2024"),
                        "cagr_mature": P({"dist": "uniform", "min": 0.25, "max": 0.29},
                                         src="Link et al., 2024"),
                    },
                    "fc": {
                        "components": {
                            "fc":                    {"type": "converter",    "capacity": 880},
                            "motor":                 {"type": "converter",    "capacity": 880},
                            "electronic_controller": {"type": "converter"},
                            "h2_350bar":             {"type": "ess",          "capacity": 50},
                            "battery":               {"type": "ess",          "capacity": 5},
                            "electric_transmission": {"type": "transmission"},
                        },
                        "fuels": {"h2": {"proportion": 1.0}},
                        "regen_efficiency": P(0.71, src="Table 16", notes="power-limited"),
                        "accessory_load":   P(3400, src="Ramesh Babu et al., 2025", units="W"),
                        "running_cost":     P(0.14, src="H. Zhao et al., 2018", units="CAD/km"),
                        "init_market_limit": P(0.02, notes="model internal"),
                        "cagr_nacent": P({"dist": "uniform", "min": 0.35, "max": 0.49},
                                         src="Link et al., 2024"),
                        "cagr_mature": P({"dist": "uniform", "min": 0.25, "max": 0.29},
                                         src="Link et al., 2024"),
                    },
                    "hice": {
                        "components": {
                            "ice":                     {"type": "converter"},
                            "motor":                   {"type": "converter",    "capacity": 220},
                            "h2_350bar":               {"type": "ess",          "capacity": 70},
                            "battery":                 {"type": "ess",          "capacity": 5},
                            "combustion_transmission": {"type": "transmission"},
                        },
                        "fuels": {"h2": {"proportion": 1.0}},
                        "regen_efficiency": P(0.71, src="Table 17", notes="power-limited"),
                        "accessory_load":   P(3400, src="Ramesh Babu et al., 2025", units="W"),
                        "running_cost":     P(0.17, src="H. Zhao et al., 2018", units="CAD/km"),
                        "init_market_limit": P(0.02, notes="model internal"),
                        "cagr_nacent": P({"dist": "uniform", "min": 0.44, "max": 0.54},
                                         src="MarketsandMarkets, 2024"),
                        "cagr_mature": P({"dist": "uniform", "min": 0.34, "max": 0.38},
                                         src="MarketsandMarkets, 2024"),
                    },
                    "dhice": {
                        "components": {
                            "ice":                     {"type": "converter"},
                            "diesel_tank":             {"type": "ess",          "capacity": 500},
                            "h2_350bar":               {"type": "ess",          "capacity": 20},
                            "combustion_transmission": {"type": "transmission"},
                            "after_treatment":         {"type": "accessories"},
                        },
                        "fuels": {
                            "diesel": {"proportion": 0.75},
                            "h2":     {"proportion": 0.25},
                        },
                        "regen_efficiency": P(0.0),
                        "accessory_load":   P(4250, src="Ramesh Babu et al., 2025", units="W"),
                        "running_cost":     P(0.17, src="H. Zhao et al., 2018", units="CAD/km"),
                        "init_market_limit": P(0.02, notes="model internal"),
                        "cagr_nacent": P({"dist": "uniform", "min": 0.44, "max": 0.54},
                                         src="MarketsandMarkets, 2024"),
                        "cagr_mature": P({"dist": "uniform", "min": 0.34, "max": 0.38},
                                         src="MarketsandMarkets, 2024"),
                    },
                },
            },

            "straight": {
                "shared": {
                    "max_age":               P(25,         notes="model internal"),
                    "activity_proportion":   P(0.061893,   src="National Research Council, 2010; NRCan, 2025; Statistics Canada, 2009"),
                    "default_unloaded_mass": P(9857,       units="kg", notes="model internal"),
                    "gvwl":                  P(24250,      src="COMT, 2019", units="kg",
                                               notes="Category 5: Straight Truck"),
                    "target_distance": P(
                        {"array": "logistic", "max_val": 49003, "min_val": 4104,
                         "k": 0.372, "x0": 7.62},
                        src="Statistics Canada, 2009", units="km"),
                    "revenue_per_tkm":    P(0.60, src="Table 21", units="CAD/t-km"),
                    "trailers_per_truck": P(0,    src="Table 13",
                                            notes="straight trucks have no trailer"),
                    "drive_cycle": P(
                        {"array": "constant", "value": "short_haul"},
                        notes="model internal"),
                    "survival_rate": P(
                        {"array": "linspace", "start": 1.0, "end": 0.0},
                        src="Statistics Canada, 2009"),
                    "frontal_area":       P(9.2,   src="National Academics, 2020", units="m2"),
                    "roll_coef":          P(0.0054, notes="model internal"),
                    "frame_mass":         P(8600,  src="M. Wang et al., 2024", units="kg",
                                            notes="day cab * 1.46 for box and liftgate"),
                    "trailer_mass":       P(0,     src="Table 13", notes="no trailer"),
                    "tire_mass":          P(291.38, src="Argonne GREET2, 2025 sleeper tire schedule (2068.38 kg) scaled by straight/sleeper survival-weighted lifetime distance ratio (0.235) x wheel-count ratio (6/10 = 0.6; 2 steer + 4 drive per GREET's Class 6 PnD Trucks vs sleeper's 2 + 8)",
                                            units="kg", notes="lifetime tire-replacement mass, not instantaneous physical mass"),
                    "mass_correction":    P(0.2,   src="Gilleon et al., 2022"),
                    "p_weighed_out":      P(0.3,   src="EPA, 2011"),
                    "driver_cost":        P(0.50, src="Table 21", units="CAD/km",
                                            notes="informed by communication with BC Trucking Association"),
                    "drag_coef": P(
                        {"dist": "interp",
                         "2000": {"dist": "const",   "val": 0.75},
                         "2025": {"dist": "const",   "val": 0.65},
                         "2050": {"dist": "uniform", "min": 0.50, "max": 0.60}},
                        src="UNREF -- paper (Table 13) shows 2025=0.60; params.py uses 0.65. Marcinkoski et al., 2019"),
                    "pollution_cost": {
                        "NOX":  P(44051,  notes="model internal; not in Appendix A"),
                        "NMVC": P(2482,   notes="model internal; not in Appendix A"),
                        "SO2":  P(25542,  notes="model internal; not in Appendix A"),
                        "PM":   P(254383, notes="model internal; not in Appendix A"),
                        "PMNE": P(46120,  notes="model internal; not in Appendix A"),
                    },
                    "base_cost": P(105000, src="H. Zhao et al., 2018; Transport Canada, 2018",
                                   units="CAD"),
                },
                "powertrains": {
                    "dice": {
                        "components": {
                            "ice":                     {"type": "converter"},
                            "diesel_tank":             {"type": "ess",          "capacity": 250},
                            "combustion_transmission": {"type": "transmission"},
                            "after_treatment":         {"type": "accessories"},
                        },
                        "fuels": {"diesel": {"proportion": 1.0}},
                        "regen_efficiency": P(0.0),
                        "accessory_load":   P(4250, src="Ramesh Babu et al., 2025", units="W"),
                        "running_cost":     P(0.17, src="H. Zhao et al., 2018", units="CAD/km"),
                        "init_market_limit": P(1.0, notes="model internal"),
                        "cagr_nacent": P({"dist": "uniform", "min": 0.44, "max": 0.54},
                                         src="MarketsandMarkets, 2024"),
                        "cagr_mature": P({"dist": "uniform", "min": 0.34, "max": 0.38},
                                         src="MarketsandMarkets, 2024"),
                    },
                    "he": {
                        "components": {
                            "ice":                     {"type": "converter"},
                            "motor":                   {"type": "converter", "capacity": 220},
                            "diesel_tank":             {"type": "ess",       "capacity": 500},
                            "battery":                 {"type": "ess",       "capacity": 5},
                            "combustion_transmission": {"type": "transmission"},
                            "after_treatment":         {"type": "accessories"},
                        },
                        "fuels": {"diesel": {"proportion": 1.0}},
                        "regen_efficiency": P(0.71, src="Table 14", notes="power-limited"),
                        "accessory_load":   P(3400, src="Ramesh Babu et al., 2025", units="W"),
                        "running_cost":     P(0.17, src="H. Zhao et al., 2018", units="CAD/km"),
                        "init_market_limit": P(0.02, notes="model internal"),
                        "cagr_nacent": P({"dist": "uniform", "min": 0.44, "max": 0.54},
                                         src="MarketsandMarkets, 2024"),
                        "cagr_mature": P({"dist": "uniform", "min": 0.34, "max": 0.38},
                                         src="MarketsandMarkets, 2024"),
                    },
                    "phe": {
                        "components": {
                            "ice":                     {"type": "converter"},
                            "motor":                   {"type": "converter", "capacity": 350},
                            "diesel_tank":             {"type": "ess",       "capacity": 500},
                            "battery":                 {"type": "ess",       "capacity": 150},
                            "combustion_transmission": {"type": "transmission"},
                            "after_treatment":         {"type": "accessories"},
                        },
                        "fuels": {
                            "slow_charge": {"proportion": 0.5},
                            "diesel":      {"proportion": 0.5},
                        },
                        "regen_efficiency": P(0.71, src="Table 14", notes="power-limited"),
                        "accessory_load":   P(3400, src="Ramesh Babu et al., 2025", units="W"),
                        "running_cost":     P(0.17, src="H. Zhao et al., 2018", units="CAD/km"),
                        "init_market_limit": P(0.02, notes="model internal"),
                        "cagr_nacent": P({"dist": "uniform", "min": 0.44, "max": 0.54},
                                         src="MarketsandMarkets, 2024"),
                        "cagr_mature": P({"dist": "uniform", "min": 0.34, "max": 0.38},
                                         src="MarketsandMarkets, 2024"),
                    },
                    "be": {
                        "components": {
                            "motor":                 {"type": "converter",    "capacity": 880},
                            "electronic_controller": {"type": "converter"},
                            "battery":               {"type": "ess",          "capacity": 500},
                            "electric_transmission": {"type": "transmission"},
                        },
                        "fuels": {"slow_charge": {"proportion": 1.0}},
                        "regen_efficiency": P(0.71, src="Table 15", notes="power-limited"),
                        "accessory_load":   P(6900, src="Ramesh Babu et al., 2025", units="W"),
                        "running_cost":     P(0.12, src="H. Zhao et al., 2018", units="CAD/km"),
                        "init_market_limit": P(0.02, notes="model internal"),
                        "cagr_nacent": P({"dist": "uniform", "min": 0.35, "max": 0.49},
                                         src="Link et al., 2024"),
                        "cagr_mature": P({"dist": "uniform", "min": 0.25, "max": 0.29},
                                         src="Link et al., 2024"),
                    },
                    "fc": {
                        "components": {
                            "fc":                    {"type": "converter",    "capacity": 880},
                            "motor":                 {"type": "converter",    "capacity": 880},
                            "electronic_controller": {"type": "converter"},
                            "h2_350bar":             {"type": "ess",          "capacity": 50},
                            "battery":               {"type": "ess",          "capacity": 5},
                            "electric_transmission": {"type": "transmission"},
                        },
                        "fuels": {"h2": {"proportion": 1.0}},
                        "regen_efficiency": P(0.71, src="Table 16", notes="power-limited"),
                        "accessory_load":   P(3400, src="Ramesh Babu et al., 2025", units="W"),
                        "running_cost":     P(0.14, src="H. Zhao et al., 2018", units="CAD/km"),
                        "init_market_limit": P(0.02, notes="model internal"),
                        "cagr_nacent": P({"dist": "uniform", "min": 0.35, "max": 0.49},
                                         src="Link et al., 2024"),
                        "cagr_mature": P({"dist": "uniform", "min": 0.25, "max": 0.29},
                                         src="Link et al., 2024"),
                    },
                    "hice": {
                        "components": {
                            "ice":                     {"type": "converter"},
                            "motor":                   {"type": "converter",    "capacity": 220},
                            "h2_350bar":               {"type": "ess",          "capacity": 50},
                            "battery":                 {"type": "ess",          "capacity": 5},
                            "combustion_transmission": {"type": "transmission"},
                        },
                        "fuels": {"h2": {"proportion": 1.0}},
                        "regen_efficiency": P(0.71, src="Table 17", notes="power-limited"),
                        "accessory_load":   P(3400, src="Ramesh Babu et al., 2025", units="W"),
                        "running_cost":     P(0.17, src="H. Zhao et al., 2018", units="CAD/km"),
                        "init_market_limit": P(0.02, notes="model internal"),
                        "cagr_nacent": P({"dist": "uniform", "min": 0.44, "max": 0.54},
                                         src="MarketsandMarkets, 2024"),
                        "cagr_mature": P({"dist": "uniform", "min": 0.34, "max": 0.38},
                                         src="MarketsandMarkets, 2024"),
                    },
                    "dhice": {
                        "components": {
                            "ice":                     {"type": "converter"},
                            "diesel_tank":             {"type": "ess",          "capacity": 500},
                            "h2_350bar":               {"type": "ess",          "capacity": 20},
                            "combustion_transmission": {"type": "transmission"},
                            "after_treatment":         {"type": "accessories"},
                        },
                        "fuels": {
                            "diesel": {"proportion": 0.75},
                            "h2":     {"proportion": 0.25},
                        },
                        "regen_efficiency": P(0.0),
                        "accessory_load":   P(4250, src="Ramesh Babu et al., 2025", units="W"),
                        "running_cost":     P(0.14, src="H. Zhao et al., 2018", units="CAD/km"),
                        "init_market_limit": P(0.02, notes="model internal"),
                        "cagr_nacent": P({"dist": "uniform", "min": 0.44, "max": 0.54},
                                         src="MarketsandMarkets, 2024"),
                        "cagr_mature": P({"dist": "uniform", "min": 0.34, "max": 0.38},
                                         src="MarketsandMarkets, 2024"),
                    },
                },
            },

        },
    },
}
